version: "3"
services:
  nexus:
    image: sonatype/nexus3:3.16.0
    container_name: nexus
    ports:
      - 8081:8081
    environment:
      - NEXUS_CONTEXT=nexus
  server:
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "22:22"